name: OpenWrt Build

on:
  workflow_dispatch:  # Trigger the workflow manually
  push:
    branches:
      - main   # Trigger workflow on changes to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up OpenWrt ImageBuilder
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libncurses5-dev gawk git unzip wget curl python3 rsync
          wget https://downloads.openwrt.org/releases/22.03.5/targets/x86/64/openwrt-imagebuilder-22.03.5-x86-64.Linux-x86_64.tar.xz
          tar -xf openwrt-imagebuilder-22.03.5-x86-64.Linux-x86_64.tar.xz
          mv openwrt-imagebuilder-22.03.5-x86-64.Linux-x86_64 imagebuilder

      - name: Build Custom OpenWrt Image
        run: |
          cd imagebuilder
          make image PROFILE=generic PACKAGES="kmod-iwlwifi kmod-iwlwifi-ax210 kmod-igc luci luci-ssl" FILES=../files

      - name: Upload firmware
        uses: actions/upload-artifact@v3
        with:
          name: openwrt-image
          path: imagebuilder/bin/targets/x86/64/*.img.gz
